### ISSUE TITLE
Doesn't seem to work all that well with Radarr

### ISSUE THREAD

**Issue by derekantrican** [Bloc67/Sonarr-Dark-Style#2]
I know this is technically "**Sonarr**-Dark-Style" but it'd be nice if it worked with all the other Sonarr forks too. I'm personally using Readarr and Radarr and it works great with Readarr (v0.1.1.1320) but doesn't seem to work that well with Radarr (v4.1.0.6175):

![image](https://user-images.githubusercontent.com/1558019/188343342-75cc7bc7-ea60-40c7-8e2a-68cc5c7af744.png)

It's mostly the "monitor status" area below the movies. I'll do a little digging and see what I can find.

**Comment by derekantrican** [comment]
Well that didn't take long. I just added `.MovieIndexPoster-title-cenr\+,` to this block:

```css
.SeriesIndexPoster-title-1h3SR,
.SeriesIndexPoster-nextAiring-2nqSB,
.MovieIndexPoster-title-cenr\+,
.EpisodeDetailsModalContent-selectedTab-_FbVg,
.Input-input-25Gr2,
.Card-card-1klRK, 
.Button-default-342be,
.AddNewSeries-searchIconContainer-2rJMO {
    border: none;
    background: #234;
    color: #fff;
}
```
