### ISSUE TITLE
"Series ended" corner is ruined with style

### ISSUE THREAD

**Issue by derekantrican** [Bloc67/Sonarr-Dark-Style#3]
With style off:

![image](https://user-images.githubusercontent.com/1558019/188343952-35ef90ea-6e64-4bf9-aaff-6208ef9041e2.png)

With style on:

![image](https://user-images.githubusercontent.com/1558019/188343975-b0eafb93-7aa1-4193-81d1-868856d336c3.png)

This occurs because of the `.PageContent-content-B3Bmu *` selector. Solution I used was to add back the default to the stylus style:

```css
.SeriesIndexPoster-ended-3J4F_ {
    border-color: transparent #f05050 transparent transparent;
}
```
